// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbauhqmmivavrvsghkdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRiYXVocW1taXZhdnJ2c2doa2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MjkxMjksImV4cCI6MjA2MzAwNTEyOX0.H5cSr4EFbEBQq3yKFB_y93YdktQp1LXXbBa-fxmhSi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);